name:                haskell-api-example
version:             0.1.0.0
github:              Kitanotori/haskell-api-example
category:            Web
synopsis:            An example on how to implement a simple REST API in Haskell.
homepage:            https://github.com/Kitanotori/haskell-api-example#README
license:             Apache
license-file:        LICENSE
author:              Petri Kivikangas
maintainer:          petri.kivikangas@protonmail.com
copyright:           2019 Petri Kivikangas

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Kitanotori/haskell-api-example#README>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - servant-server
  - wai
  - warp

executables:
  haskell-api-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Weverything
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-api-example

tests:
  haskell-api-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Weverything
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - haskell-api-example
    - hlint
    - hspec
    - hspec-discover
    - hspec-wai
    - hspec-wai-json
